#!/usr/bin/env python3
"""Generate src/mojo_dllm/tokenizer/unicode_tables.mojo from llama.cpp's tables.

usage: gen_unicode_tables.py PATH/TO/llama.cpp/src/unicode-data.cpp

The pre-tokenizer must classify code points exactly as llama.cpp does, or
prompts tokenize differently and every comparison downstream is void. So the
tables come from llama.cpp's own `unicode_ranges_flags` and
`unicode_set_whitespace`, not from Python's unicodedata (a different Unicode
version on most machines).

Only non-ASCII code points are tabulated; ASCII is classified in code.
"""

from __future__ import annotations

import pathlib
import re
import sys

NUMBER = 0x0002
LETTER = 0x0004


def ranges_with(flags_ranges: list[tuple[int, int]], bit: int) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for i, (start, flags) in enumerate(flags_ranges):
        end = flags_ranges[i + 1][0] - 1 if i + 1 < len(flags_ranges) else 0x10FFFF
        if flags & bit and end >= 128:
            lo = max(start, 128)
            if out and out[-1][1] + 1 == lo:
                out[-1] = (out[-1][0], end)
            else:
                out.append((lo, end))
    return out


def emit(name: str, ranges: list[tuple[int, int]]) -> str:
    flat = ", ".join(f"{lo}, {hi}" for lo, hi in ranges)
    return f"comptime {name}: List[Int] = [{flat}]\n"


def main() -> int:
    src = pathlib.Path(sys.argv[1]).read_text()
    block = src.split("unicode_ranges_flags = {", 1)[1].split("};", 1)[0]
    pairs = [(int(a, 16), int(b, 16)) for a, b in re.findall(r"\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}", block)]
    ws_block = src.split("unicode_set_whitespace = {", 1)[1].split("};", 1)[0]
    ws = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", ws_block)]
    letters = ranges_with(pairs, LETTER)
    numbers = ranges_with(pairs, NUMBER)
    ws_hi = sorted(c for c in ws if c >= 128)
    out = pathlib.Path(__file__).resolve().parent.parent / "src/mojo_dllm/tokenizer/unicode_tables.mojo"
    text = (
        '"""Code point classes for the pre-tokenizer. GENERATED by scripts/gen_unicode_tables.py\n'
        "from llama.cpp's src/unicode-data.cpp; do not edit by hand.\n\n"
        "Each table is flattened [lo0, hi0, lo1, hi1, ...] inclusive ranges over\n"
        'code points >= 128, sorted, non-overlapping."""\n\n'
        + emit("LETTER_RANGES", letters)
        + "\n"
        + emit("NUMBER_RANGES", numbers)
        + "\n"
        + f"comptime WHITESPACE_HIGH: List[Int] = [{', '.join(str(c) for c in ws_hi)}]\n"
    )
    out.write_text(text)
    print(f"letters {len(letters)} ranges, numbers {len(numbers)} ranges, whitespace {len(ws_hi)} -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
